name: Jobs Notif
on:
  push:
  schedule:
    - cron: '0 5 15 4 *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start Notif
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git clone https://"${GH_TOKEN}":x-oauth-basic@github.com/XSans02/jobs-notif
        cd jobs-notif
        bash bday
